name: Run Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.15.0' # Replace with your Node.js version

    - name: Install Dependencies
      run: npm ci

    - name: Start Application
      run: npm start # This is your start script

    - name: Wait for Server to Respond
      uses: jakejarvis/wait-action@master
      with:
        url: http://https://villagerchess.netlify.app/ # Replace with your application URL

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v2
      with:
        start: npm start # This is your start script
        wait-on: 'http://https://villagerchess.netlify.app/' # Replace with your application URL